name: nightly-neon-xtn

on:
  schedule:
    - cron: "52 1 * * *"
  workflow_dispatch:

env:
  BUILDDIR: /build
  SRCDIR: ${{ github.workspace }}
  CMAKE_ARGS: |
    -DWEBVIEW_FORCE_WEBKIT=1
    -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    -DWITH_PYTHONQT=OFF"
    -DCMAKE_BUILD_TYPE=Debug

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://kdeneon/plasma:user
      options: --tmpfs /build:rw --user 0:0
    steps:
      - name: "fetch artifacts"
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: nightly-neon.yml
          workflow_conclusion: success
          branch: calamares
          name: calamares-tarball
          path: ${{ env.BUILDDIR }}
          repo: calamares/calamares
      - name: "prepare env"
        uses: calamares/actions/prepare-neon@v2
      - name: "prepare source"
        uses: actions/checkout@v2
      - name: "prepare artifacts"
        run: tar xvzf "$BUILDDIR/calamares.tar.gz" -C / --strip-components 1
      - name: "build"
        id: build
        uses: calamares/actions/generic-build@v2
      - name: "notify: ok"
        if: ${{ success() && github.repository == 'calamares/calamares-extensions' }}
        uses: calamares/actions/matrix-notify@v2
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: "OK ${{ github.workflow }} in ${{ github.repository }} ${{ steps.build.outputs.git_summary }}"
      - name: "notify: fail"
        if: ${{ failure() && github.repository == 'calamares/calamares' }}
        uses: calamares/actions/matrix-notify@v2
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: "FAIL ${{ github.workflow }} in ${{ github.repository }} ${{ steps.build.outputs.git_summary}}"





